apiVersion: apps/v1
kind: Deployment
metadata:
  name: pela-app
  namespace: dba
  labels:
    app: pela
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pela
  template:
    metadata:
      labels:
        app: pela
    spec:
      containers:
      - name: pela-container
        image: erenyormaz/pela-log-analyzer:v1.6.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: TZ
          value: "Europe/Istanbul"
        volumeMounts:
        - name: ssh-key-vol
          mountPath: /app/keys
          readOnly: true
      volumes:
      - name: ssh-key-vol
        secret:
          secretName: ssh-key-secret
          defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: pela-service
  namespace: dba
spec:
  selector:
    app: pela
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pela-ingress
  namespace: dba
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: pela.dev.hostname.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pela-service
            port:
              number: 80